/**
 * 自動產生檔案 —— 請勿手動編輯。
 *
 * 來源：src/tokens/tokens.json（Figma Variables 的鏡像）
 * 產生：npm run tokens:build
 */

/** token 名稱 -> CSS var() 參照。在 JS 端組樣式時用這個，才不會寫死數值。 */
export const token = {
  'color-primary-100': 'var(--lds-color-primary-100)',
  'color-primary-200': 'var(--lds-color-primary-200)',
  'color-primary-300': 'var(--lds-color-primary-300)',
  'color-primary-400': 'var(--lds-color-primary-400)',
  'color-primary-700': 'var(--lds-color-primary-700)',
  'color-primary-800': 'var(--lds-color-primary-800)',
  'color-primary-900': 'var(--lds-color-primary-900)',
  'color-grey-100': 'var(--lds-color-grey-100)',
  'color-grey-200': 'var(--lds-color-grey-200)',
  'color-grey-300': 'var(--lds-color-grey-300)',
  'color-grey-400': 'var(--lds-color-grey-400)',
  'color-grey-600': 'var(--lds-color-grey-600)',
  'color-grey-700': 'var(--lds-color-grey-700)',
  'color-grey-900': 'var(--lds-color-grey-900)',
  'color-grey-white': 'var(--lds-color-grey-white)',
  'color-success-text': 'var(--lds-color-success-text)',
  'color-success-icon': 'var(--lds-color-success-icon)',
  'color-destruct-text': 'var(--lds-color-destruct-text)',
  'color-destruct-icon': 'var(--lds-color-destruct-icon)',
  'spacing-0': 'var(--lds-spacing-0)',
  'spacing-xs': 'var(--lds-spacing-xs)',
  'spacing-s': 'var(--lds-spacing-s)',
  'spacing-m': 'var(--lds-spacing-m)',
  'spacing-l': 'var(--lds-spacing-l)',
  'spacing-xl': 'var(--lds-spacing-xl)',
  'spacing-3xl': 'var(--lds-spacing-3xl)',
  'spacing-4xl': 'var(--lds-spacing-4xl)',
  'radius-0': 'var(--lds-radius-0)',
  'radius-xs': 'var(--lds-radius-xs)',
  'radius-s': 'var(--lds-radius-s)',
  'radius-l': 'var(--lds-radius-l)',
  'radius-rounded': 'var(--lds-radius-rounded)',
  'font-family-sans': 'var(--lds-font-family-sans)',
  'font-family-mono': 'var(--lds-font-family-mono)',
  'font-size-h1': 'var(--lds-font-size-h1)',
  'font-size-h2': 'var(--lds-font-size-h2)',
  'font-size-h3': 'var(--lds-font-size-h3)',
  'font-size-h4': 'var(--lds-font-size-h4)',
  'font-size-label': 'var(--lds-font-size-label)',
  'font-size-body': 'var(--lds-font-size-body)',
  'font-line-height-h1': 'var(--lds-font-line-height-h1)',
  'font-line-height-h2': 'var(--lds-font-line-height-h2)',
  'font-line-height-h3': 'var(--lds-font-line-height-h3)',
  'font-line-height-h4': 'var(--lds-font-line-height-h4)',
  'font-line-height-label': 'var(--lds-font-line-height-label)',
  'font-line-height-body': 'var(--lds-font-line-height-body)',
  'font-weight-regular': 'var(--lds-font-weight-regular)',
  'font-weight-medium': 'var(--lds-font-weight-medium)',
  'font-weight-bold': 'var(--lds-font-weight-bold)',
  'typography-headline-1': 'var(--lds-typography-headline-1)',
  'typography-headline-1-font-size': 'var(--lds-typography-headline-1-font-size)',
  'typography-headline-1-line-height': 'var(--lds-typography-headline-1-line-height)',
  'typography-headline-1-font-weight': 'var(--lds-typography-headline-1-font-weight)',
  'typography-headline-2': 'var(--lds-typography-headline-2)',
  'typography-headline-2-font-size': 'var(--lds-typography-headline-2-font-size)',
  'typography-headline-2-line-height': 'var(--lds-typography-headline-2-line-height)',
  'typography-headline-2-font-weight': 'var(--lds-typography-headline-2-font-weight)',
  'typography-headline-3': 'var(--lds-typography-headline-3)',
  'typography-headline-3-font-size': 'var(--lds-typography-headline-3-font-size)',
  'typography-headline-3-line-height': 'var(--lds-typography-headline-3-line-height)',
  'typography-headline-3-font-weight': 'var(--lds-typography-headline-3-font-weight)',
  'typography-headline-4': 'var(--lds-typography-headline-4)',
  'typography-headline-4-font-size': 'var(--lds-typography-headline-4-font-size)',
  'typography-headline-4-line-height': 'var(--lds-typography-headline-4-line-height)',
  'typography-headline-4-font-weight': 'var(--lds-typography-headline-4-font-weight)',
  'typography-body-l': 'var(--lds-typography-body-l)',
  'typography-body-l-font-size': 'var(--lds-typography-body-l-font-size)',
  'typography-body-l-line-height': 'var(--lds-typography-body-l-line-height)',
  'typography-body-l-font-weight': 'var(--lds-typography-body-l-font-weight)',
  'typography-body-m': 'var(--lds-typography-body-m)',
  'typography-body-m-font-size': 'var(--lds-typography-body-m-font-size)',
  'typography-body-m-line-height': 'var(--lds-typography-body-m-line-height)',
  'typography-body-m-font-weight': 'var(--lds-typography-body-m-font-weight)',
  'elevation-low': 'var(--lds-elevation-low)',
  'elevation-medium': 'var(--lds-elevation-medium)',
  'elevation-high': 'var(--lds-elevation-high)',
} as const;

/** token 名稱 -> 實際字面值。僅供文件展示、測試比對用，元件請勿直接引用。 */
export const rawToken = {
  '--lds-color-primary-100': "#e1e8f0",
  '--lds-color-primary-200': "#c3d1e0",
  '--lds-color-primary-300': "#a3bbd6",
  '--lds-color-primary-400': "#93aecc",
  '--lds-color-primary-700': "#4d7099",
  '--lds-color-primary-800': "#355a85",
  '--lds-color-primary-900': "#254973",
  '--lds-color-grey-100': "#dcdcdc",
  '--lds-color-grey-200': "#c3c3c3",
  '--lds-color-grey-300': "#aaaaaa",
  '--lds-color-grey-400': "#929292",
  '--lds-color-grey-600': "#737373",
  '--lds-color-grey-700': "#4e4e4e",
  '--lds-color-grey-900': "#262626",
  '--lds-color-grey-white': "#fafafa",
  '--lds-color-success-text': "#365c00",
  '--lds-color-success-icon': "#5d960e",
  '--lds-color-destruct-text': "#ab0000",
  '--lds-color-destruct-icon': "#c74040",
  '--lds-spacing-0': "0px",
  '--lds-spacing-xs': "4px",
  '--lds-spacing-s': "8px",
  '--lds-spacing-m': "12px",
  '--lds-spacing-l': "16px",
  '--lds-spacing-xl': "24px",
  '--lds-spacing-3xl': "48px",
  '--lds-spacing-4xl': "64px",
  '--lds-radius-0': "0px",
  '--lds-radius-xs': "4px",
  '--lds-radius-s': "8px",
  '--lds-radius-l': "16px",
  '--lds-radius-rounded': "9999px",
  '--lds-font-family-sans': "\"Noto Sans TC\", \"PingFang TC\", \"Microsoft JhengHei\", sans-serif",
  '--lds-font-family-mono': "\"SF Mono\", ui-monospace, Menlo, Consolas, monospace",
  '--lds-font-size-h1': "32px",
  '--lds-font-size-h2': "24px",
  '--lds-font-size-h3': "20px",
  '--lds-font-size-h4': "16px",
  '--lds-font-size-label': "20px",
  '--lds-font-size-body': "16px",
  '--lds-font-line-height-h1': "40px",
  '--lds-font-line-height-h2': "36px",
  '--lds-font-line-height-h3': "30px",
  '--lds-font-line-height-h4': "24px",
  '--lds-font-line-height-label': "30px",
  '--lds-font-line-height-body': "24px",
  '--lds-font-weight-regular': "400",
  '--lds-font-weight-medium': "500",
  '--lds-font-weight-bold': "700",
  '--lds-typography-headline-1': "700 32px/40px var(--lds-font-family-sans)",
  '--lds-typography-headline-1-font-size': "32px",
  '--lds-typography-headline-1-line-height': "40px",
  '--lds-typography-headline-1-font-weight': "700",
  '--lds-typography-headline-2': "500 24px/36px var(--lds-font-family-sans)",
  '--lds-typography-headline-2-font-size': "24px",
  '--lds-typography-headline-2-line-height': "36px",
  '--lds-typography-headline-2-font-weight': "500",
  '--lds-typography-headline-3': "500 20px/30px var(--lds-font-family-sans)",
  '--lds-typography-headline-3-font-size': "20px",
  '--lds-typography-headline-3-line-height': "30px",
  '--lds-typography-headline-3-font-weight': "500",
  '--lds-typography-headline-4': "500 16px/24px var(--lds-font-family-sans)",
  '--lds-typography-headline-4-font-size': "16px",
  '--lds-typography-headline-4-line-height': "24px",
  '--lds-typography-headline-4-font-weight': "500",
  '--lds-typography-body-l': "400 20px/30px var(--lds-font-family-sans)",
  '--lds-typography-body-l-font-size': "20px",
  '--lds-typography-body-l-line-height': "30px",
  '--lds-typography-body-l-font-weight': "400",
  '--lds-typography-body-m': "400 16px/24px var(--lds-font-family-sans)",
  '--lds-typography-body-m-font-size': "16px",
  '--lds-typography-body-m-line-height': "24px",
  '--lds-typography-body-m-font-weight': "400",
  '--lds-elevation-low': "0 1px 4px 0 #dcdcdc",
  '--lds-elevation-medium': "2px 2px 4px 0 #c3c3c3, 0 4px 16px 0 #c3c3c3",
  '--lds-elevation-high': "0 3px 24px 0 #c3c3c3, 0 3px 6px 0 #dcdcdc",
} as const;

export type TokenName = keyof typeof token;
export type CssVarName = keyof typeof rawToken;
